# Generated by Django 6.0.4 on 2026-05-24 01:33

import clubs.models
import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('repetition', models.CharField(blank=True, choices=[('WEEKLY', 'Weekly'), ('BIWEEKLY', 'Biweekly'), ('MONTHLY', 'Monthly')], max_length=10)),
                ('image', models.ImageField(default='clubs/default.png', upload_to=clubs.models.get_upload_path_club)),
                ('classroom_code', models.CharField(blank=True, max_length=10)),
                ('day_of_meeting', models.CharField(blank=True, choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday')], max_length=10)),
                ('time', models.TimeField(blank=True, null=True)),
                ('room_num', models.IntegerField(blank=True, null=True)),
                ('teacher_advisor', models.CharField(blank=True, max_length=20)),
                ('category', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.CreateModel(
            name='ClubGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=clubs.models.get_upload_path_club_gallery)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('category', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleryImage', to='clubs.club')),
            ],
        ),
        migrations.CreateModel(
            name='ClubSocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(choices=[('IG', 'Instagram'), ('GH', 'GitHub'), ('YT', 'YouTube'), ('TT', 'TikTok'), ('DC', 'Discord'), ('TR', 'Threads'), ('FB', 'Facebook'), ('X', 'Twitter/X'), ('LI', 'LinkedIn'), ('WS', 'Website'), ('OT', 'Other')], default='OT', max_length=2)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socialMedia', to='clubs.club')),
            ],
        ),
    ]
