# Generated by Django 6.0.5 on 2026-05-24 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='preview_description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
