# Generated by Django 6.0.5 on 2026-05-27 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_club_preview_description'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField()),
                ('site', models.CharField(choices=[('IG', 'Instagram'), ('GH', 'GitHub'), ('YT', 'YouTube'), ('TT', 'TikTok'), ('DC', 'Discord'), ('TR', 'Threads'), ('FB', 'Facebook'), ('X', 'Twitter/X'), ('LI', 'LinkedIn'), ('WS', 'Website'), ('OT', 'Other')], default='OT', max_length=2)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.DeleteModel(
            name='ClubSocialMedia',
        ),
        migrations.AddIndex(
            model_name='socialmedia',
            index=models.Index(fields=['content_type', 'object_id'], name='clubs_socia_content_cc271f_idx'),
        ),
    ]
