# Generated by Django 6.0.5 on 2026-06-01 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_socialmedia_delete_clubsocialmedia_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='socialmedia',
            name='clubs_socia_content_cc271f_idx',
        ),
        migrations.DeleteModel(
            name='SocialMedia',
        ),
    ]
