# Generated by Django 6.0.5 on 2026-06-07 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0016_alter_club_announcement_alter_club_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='application_form_link',
            field=models.URLField(blank=True, help_text='This can be either a google classroom invite link or a application form link', max_length=250),
        ),
    ]
