# Generated by Django 6.0.5 on 2026-05-27 18:15

import address.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0003_auto_20200830_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintainance_mode', models.BooleanField(default=False)),
                ('site_name', models.CharField(default='SCHOOL STUCO', max_length=50)),
                ('favicon', models.ImageField(default='management/default.png', upload_to='management/')),
                ('stuco_image', models.ImageField(default='management/default.png', upload_to='management/')),
                ('about_stuco', models.TextField(blank=True, max_length=500)),
                ('about_school', models.TextField(blank=True, max_length=500)),
                ('school_location', address.models.AddressField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='address.address')),
            ],
            options={
                'verbose_name': 'Site Configuration',
            },
        ),
    ]
