# Generated by Django 6.0.5 on 2026-06-01 02:54

import django.db.models.deletion
import osm_field.fields
import osm_field.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintainance_mode', models.BooleanField(default=False)),
                ('site_name', models.CharField(default='SCHOOL STUCO', max_length=50)),
                ('favicon', models.ImageField(default='management/default.png', upload_to='management/')),
                ('stuco_image', models.ImageField(default='management/default.png', upload_to='management/')),
                ('about_stuco', models.TextField(blank=True, max_length=500)),
                ('about_school', models.TextField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'Site Configuration',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', osm_field.fields.OSMField(lat_field='location_lat', lon_field='location_lon')),
                ('location_lat', osm_field.fields.LatitudeField(validators=[osm_field.validators.validate_latitude])),
                ('location_lon', osm_field.fields.LongitudeField(validators=[osm_field.validators.validate_longitude])),
                ('object_id', models.PositiveBigIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField()),
                ('site', models.CharField(choices=[('IG', 'Instagram'), ('GH', 'GitHub'), ('YT', 'YouTube'), ('TT', 'TikTok'), ('DC', 'Discord'), ('TR', 'Threads'), ('FB', 'Facebook'), ('X', 'Twitter/X'), ('LI', 'LinkedIn'), ('WS', 'Website'), ('OT', 'Other')], default='OT', max_length=2)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='management__content_bb9b43_idx')],
            },
        ),
    ]
