# Generated by Django 6.0.5 on 2026-05-24 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0001_initial'),
        ('clubs', '0002_club_preview_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='club',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clubs.club'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='calendar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calendars.calendar'),
        ),
    ]
