# Generated by Django 6.0.5 on 2026-05-24 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0002_calendar_club_calendarevent_calendar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='timezone',
            field=models.TextField(default='america/toronto'),
        ),
    ]
