# Generated by Django 6.0.5 on 2026-05-27 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0003_alter_calendar_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(default='Richmond Green Secondary School', max_length=50)),
                ('product', models.CharField(default='StuCo Website', max_length=50)),
                ('language', models.CharField(default='EN', max_length=2)),
            ],
            options={
                'verbose_name': 'Calendar Configuration',
            },
        ),
    ]
