# Generated by Django 6.0.5 on 2026-05-27 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0004_calendarsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarsettings',
            name='vendor',
            field=models.CharField(default='SCHOOL', max_length=50),
        ),
    ]
